DEPTAT.UI/Controllers/ExaminationController.cs
using DEPTAT.Application.DTOs.Course;
using DEPTAT.Application.DTOs.Examination;
using DEPTAT.Application.DTOs.Otp;
using DEPTAT.Application.Features.Examinations.Commands;
using DEPTAT.Application.Features.Examinations.Queries;
using DEPTAT.Application.Features.Examinations.Queries.DebtorQuery;
using DEPTAT.Application.Features.Settings.Commands.CourseCommands;
using DEPTAT.Application.Features.Settings.Commands.DepartmentCommands;
using DEPTAT.Application.Features.Settings.Commands.OtpCommands;
using DEPTAT.Application.Features.Settings.Handlers.OtpHandlers;
using DEPTAT.Application.Features.Settings.Queries.AcademicYearQuery;
using DEPTAT.Application.Features.Settings.Queries.CourseQuery;
using DEPTAT.Application.Features.Settings.Queries.DepartmentQuery;
using DEPTAT.Application.Features.Settings.Queries.OtpQuery;
using DEPTAT.Application.Features.Settings.Queries.ProgrammesQuery;
using DEPTAT.Application.Features.Students.Queries.StudentQuery;
using DEPTAT.Application.Responses;
using MediatR;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace DEPTAT.UI.Controllers
{
	[Authorize]
	public class ExaminationController : Controller
	{
		private readonly IMediator _mediator;

		public ExaminationController(IMediator mediator)
		{
			_mediator = mediator;
		}

		[Authorize]
		public IActionResult Index()
		{
			return View();
		}

		[Authorize(Roles = "Invigilator,Admin,Account,Examiner")]
		public async Task<IActionResult> SearchStudent(string studentNumber)
		{
			var data = await _mediator.Send(new GetDebtorsByStudentNumberQuery(studentNumber));
			return Ok(data);
		}

		[Authorize(Roles = "Admin, Invigilator, Examiner")]
		public async Task<IActionResult> Attendance()
		{
			var programmeList = await _mediator.Send(new GetProgrammesQuery());
			ViewBag.ProgrammeList = programmeList?.Result?.OrderByDescending(o => o.Id).ToList();

			var academicYearList = await _mediator.Send(new GetAcademicYearsQuery());
			ViewBag.AcademicYearList = academicYearList?.Result?.OrderByDescending(o => o.Id).ToList();


			return View();
		}

		[Authorize(Roles = "Admin, Examiner, Invigilator")]
		public async Task<IActionResult> GetStudentByProgramme(int ProgrammeName)
		{
			var studentListList = await _mediator.Send(new GetStudentByProgrammeQuery(ProgrammeName));
			//var data = studentListList.Result?.OrderByDescending(o => o.StudentNumber).ToList();
			return Json(studentListList);
		}

		[Authorize(Roles = "Admin,Invigilator,Examiner,Account")]
		public async Task<IActionResult> ClockStudent()
		{
			//var studentListList = await _mediator.Send(new GetStudentByProgrammeQuery(studentNumber));
			//ViewBag.StudentList = studentListList.Result?.OrderByDescending(o => o.StudentNumber).ToList();
			return View();
		}

		[Authorize(Roles = "Admin,Invigilator,Examiner")]
		[HttpPost]
		public async Task<IActionResult> ClockAttendance([FromBody] OtpDto data)
		{
			data.CurrentYear = DateTime.Now.Year;
			var command = new CreateAndUpdateOtpCommands()
			{
				OtpDto = data
			};
			var response = await _mediator.Send(command);
			return Ok(response);
			
		}

		[Authorize(Roles = "Admin,Account,Examiner")]
		public async Task<IActionResult> ViewOTP()
		{
			var otp = await _mediator.Send(new GetOtpsQuery());
			return View(otp.Result?.OrderByDescending(o => o.Id).ToList());
		}

		[Authorize(Roles = "Admin,Invigilator,Account,Examiner")]
		public async Task<IActionResult> ValidateOTP(string studentNumber, string otpCode)
		{
			var otp = await _mediator.Send(new GetValidateOTPQuery(studentNumber, otpCode));
			return Ok(otp);
		}

		[Authorize(Roles = "Admin,Invigilator")]
		[HttpPost]
		public async Task<IActionResult> TakeAttendance(CreateAttendanceDto createAttendance)
		{
			createAttendance.AnswerBookSerialNumber = FormatCurrentDateTime();
			var command = new CreateAttendanceCommand
			{
				CreateAttendanceDto = createAttendance
			};
			var response = await _mediator.Send(command);
			return Ok(response);
		}

		[Authorize(Roles = "Admin,Invigilator,Examiner")]
		[HttpGet]
		public async Task<IActionResult> AttendanceList()
		{
			var attendanceList = await _mediator.Send(new GetAttendanceQuery());
			return View(attendanceList.Result?.OrderByDescending(o => o.Id).ToList());
			
		}


		static string FormatCurrentDateTime()
		{
			// Get the current date and time
			DateTime currentDateTime = DateTime.Now;

			// Extract year, seconds, and minutes
			int year = currentDateTime.Year;
			int seconds = currentDateTime.Second;
			int minutes = currentDateTime.Minute;
			int month = currentDateTime.Month;
			int day = currentDateTime.Day;

			// Create a formatted string
			string formattedString = $"{year:D4}{month:D}{day:D}{minutes:D2}{seconds:D2}";

			return formattedString;
		}

	}
}
	

DEPTAT.UI/Controllers/ProgrammeController.cs
using DEPTAT.Application.DTOs.Programme;
using DEPTAT.Application.Features.Settings.Commands.ProgrammeCommands;
using DEPTAT.Application.Features.Settings.Queries.DepartmentQuery;
using DEPTAT.Application.Features.Settings.Queries.ProgrammesQuery;
using DEPTAT.Application.Responses;
using MediatR;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace DEPTAT.UI.Controllers
{
	[Authorize(Roles = "Admin")]
	public class ProgrammeController : Controller
	{
		private readonly IMediator _mediator;
		private readonly IHttpContextAccessor _httpContextAccessor;

		public ProgrammeController(IMediator mediator, IHttpContextAccessor httpContextAccessor)
		{
			_mediator = mediator;
			_httpContextAccessor = httpContextAccessor;
		}

		public async Task<IActionResult> Index()
		{
			var departmentList = await _mediator.Send(new GetDepartmentsQuery());
			ViewBag.DepartmentList = departmentList.Result?.OrderByDescending(o => o.Id).ToList();


			var ProgrammeName = await _mediator.Send(new GetProgrammesQuery());
			return View(ProgrammeName.Result?.OrderByDescending(o => o.Id).ToList());
		}

		[HttpPost]
		public async Task<ActionResult<BaseResponse<CreateProgrammeDto>>> CreateProgramme([FromBody] CreateProgrammeDto createProgramme)
		{
			var command = new CreateProgrammeCommand
			{
				CreateProgrammeDto = createProgramme
			};
			var response = await _mediator.Send(command);
			return Ok(response);
		}



		[HttpGet]
		public async Task<IActionResult> GetProgramme(int Id)
		{
			var Programme = await _mediator.Send(new GetProgrammeByIdQuery(Id));
			return Ok(Programme);


		}

		[HttpPut]
		public async Task<ActionResult<BaseResponse<UpdateProgrammeDto>>> UpdateProgramme([FromBody] UpdateProgrammeDto updateProgramme)
		{
			var command = new UpdateProgrammeCommand
			{
				UpdateProgrammeDto = updateProgramme
			};
			var response = await _mediator.Send(command);
			return Ok(response);
		}
		[HttpDelete]
		public async Task<ActionResult> DeleteProgramme(int id)
		{
			var command = new DeleteProgrammeCommand { Id = id };
			var response = await _mediator.Send(command);
			return Ok(response);
		}

		[HttpGet]
		public async Task<IActionResult> Detailed()
		{
			var ProgrammeName = await _mediator.Send(new GetProgrammesQuery());
			return View(ProgrammeName.Result?.OrderByDescending(o => o.Id).ToList());
		}

	}
}

DEPTAT.UI/Views/Examination/Attendance.cshtml
@*@model IEnumerable<DEPTAT.Application.Responses.DebtorsResponse>*@
@{
	var programmeList = ViewBag.ProgrammeList as List<ProgrammeResponse>;
	var academicYearList = ViewBag.AcademicYearList as List<AcademicYearResponse>;
}
<div class="container-fluid">

	<!-- Horizontal Layout -->
	<div class="row clearfix">
		<div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
			<div class="card">
				<div class="header">
					<h2>
						SELECT PROGRAMME
					</h2>
					<div align="center">
					</div>
					<ul class="header-dropdown m-r--5">
						<li class="dropdown">
						<a href="javascript:void(0);" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
						<i class="material-icons">more_vert</i>
						</a>
						<ul class="dropdown-menu pull-right">
						<li><a asp-controller="Examination" asp-action="AttendanceList">Attendance List</a></li>
						
						</ul>
						</li>
					</ul>
				</div>
				<div class="body">
					@*<form action="/target" class="dropzone" id="my-form"></form>*@
					<form class="form-horizontal" id="registerForm" method="GET">

						<div class="row clearfix">
							<div class="col-lg-2 col-md-2 col-sm-4 col-xs-4 form-control-label">
								<label for="file">Programme:</label>
							</div>
							<div class="col-sm-6">
								<select class="form-control show-tick" id="programmeId" name="ProgrammeId">
									<option value="0">-- Please select --</option>
									@foreach (var programme in programmeList)
									{
										<option value="@programme.Id">@programme.Name</option>
									}
								</select>
							</div>



						</div>
					</form>
				</div>
			</div>
		</div>
	</div>
	<!-- #END# Horizontal Layout -->
	<!-- Horizontal Layout -->
	<div class="row clearfix">
		<div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
			<div class="card">
				<div class="header">
					<h2>
						STUDENTS
					</h2>

				</div>
				<div class="body">
					<div class="row">
						<div class="col-md-12">
							<label>Settings</label>
						</div>
					</div>
					<div class="row">
						<div class="col-sm-6">
							<label>Semester</label>
							<select class="form-control show-tick" id="semesterId" name="Semester">
								<option value="0">-- Please select --</option>
									<option value="1">Semester One</option>
									<option value="e">Semester Two</option>
							</select>
						</div>
						<div class="col-sm-6">
							<label>Academic Year</label>
							<select class="form-control show-tick" id="academicYear" name="AcademicYear">
								<option value="0">-- Please select --</option>
								@foreach (var academicYear in academicYearList)
								{
									<option value="@academicYear.Id">@academicYear.Name</option>
								}
							</select>
						</div>
					</div>
					<div id="showData"></div>



				</div>
			</div>
		</div>
	</div>
	<!-- #END# Horizontal Layout -->

</div>





<script type="text/ecmascript">
	$(document).ready(function () {
		

		$('#programmeId').change(function () {
			$(".image-url").hide();
			var programme = $("#programmeId").val();
			var output = "";

			$.ajax({
				url: $('#base_url').text() + '/Examination/GetStudentByProgramme',
				type: 'json',
				type: 'GET',
				data: { ProgrammeName: programme },
				success: function (response) {
					console.log(response.result);
					if (response.isSuccess) {
						if (response.result && response.result.length > 0) {
							output += `
								<div class="list-group">
							`;

							$.each(response.result, function (index, element) {
								output += `
									
									<button type="button" id="${element.studentNumber}" class="list-group-item waves-effect edit"><span class="text-primary" data-toggle="modal" data-target="#smallModal">
									${element.studentNumber}</span> - <span>${element.fullName}</span> <span class="image-url" hidden>${element.imageUrl}</span>
									</button>
								`;
							});

							output += `
									</div>
							`;
						} else {
							output += `
								<div class="alert bg-green alert-dismissible" role="alert">
									<button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
									Sorry no records found...
								</div>
							`;
						}
					} else {
						output += `
							<div class="alert bg-red alert-dismissible" role="alert">
								<button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
								Error: ${response.message}
							</div>
						`;
					}

					$("#showData").html(output);
				},
				error: function (xhr, status, error) {
					output += `
						<div class="alert bg-red alert-dismissible" role="alert">
							<button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
							Error: ${error}
						</div>
					`;

					$("#showData").html(output);
				}
			});
		});
		
		
		//Put student to Modal
		$(document).on('click', '.edit', function(){
			var studentNumber = $(this).attr('id');
				var programmeId = $('#programmeId').val();
				var baseUrl = $('#base_url').text();
				//var semesterId = $('#semesterId').val();
				//var academicYear = $('#academicYear').val();
				 var imageUrl = $(this).find(".image-url").text();
				 $("#studentImage").html(`<img src="${baseUrl}/uploads/${imageUrl}" width="100%" height="100%" />`);

				window.academicYearToDb = $("#attendenceAcademicYear").text($('#academicYear').find('option:selected').text());
				window.academicYearToDb = $('#academicYear').val();
				
				$("#attendenceSemester").text($('#semesterId').find('option:selected').text());
				window.semesterToDb = $('#semesterId').val();
				
				$("#attendenceStudentNumber").text(studentNumber);
		
		})
		//Validate OTP
		$(document).on('click','#validateOTP',function(){
				var otpCode = $('#otpCode').val();
				var studentNumber = $('#attendenceStudentNumber').text();

				$.ajax({
				url: $('#base_url').text() + '/Examination/ValidateOTP',
				type: 'json',
				type: 'GET',
				data: { studentNumber,  otpCode},
				success: function (response) {
					console.log(response.result);
					if (response.isSuccess) {
						$("#otp-error").text(response.message);
						$("#otp-error").addClass("text-success");
					}else{
						$("#otp-error").text(response.message);
						$("#otp-error").addClass("error");
					}
				}
			});
		});
		
		//Save Attendance
		$(document).on('click','#saveAttance',function(){
			var validate = $('#otp-error').text();
			if(validate == "OTP is Valid"){
					
					var createAttendance = {
							"StudentNumber":$("#attendenceStudentNumber").text(),
							"AnswerBookSerialNumber": $("#answerBooklet").val(),
							"Semester": window.semesterToDb,
							"CourseCode": $("#courseCode").val(),
						//	"AcademicYear": window.academicYearToDb,
							"AcademicYear": $('#attendenceAcademicYear').text(),
							"OtpCode":$("#otpCode").val()

					};
					console.log(createAttendance);
					$.ajax({
			url: $('#base_url').text() + '/Examination/TakeAttendance',
			//contentType: "application/json",
			type: 'POST',

			//data: JSON.stringify(createAttendance),
			data: createAttendance,

			success: function (response) {
				if (response.isSuccess) {
					showNotificationSuccessMessage(response.message, "Success");
					//location.reload();
				} else {
					showNotificationErrorMessage("Failed", response.message, "error");
					//location.reload();
				}

			}
		})

			}else if(validate == "INVALID OTP"){
				showNotificationErrorMessage("Failed", "OTP is Invalid. You can't Proceed", "error");
			}else{
				showNotificationErrorMessage("Failed", "Please Click validate OTP before you proceed", "error");
				}
		});

	});
</script>

<div class="modal fade" id="smallModal" tabindex="-1" role="dialog">
	<div class="modal-dialog modal-sm" role="document">
		<div class="modal-content">
			<div class="modal-header">
				<h4 class="modal-title" id="smallModalLabel">Take Attendance</h4>
			</div>
			<div class="modal-body">
				<div class="thumbnail">
					<div id="studentImage"></div>
					<div class="caption">
						<h3>StudentNumber: <span id="attendenceStudentNumber"></span></h3>
						<p>
							<div class="form-group form-float">
								<div class="form-line">
									<input type="text" id="courseCode" class="form-control">
									<label class="form-label">Course Code</label>
								</div>
							</div>
							<div class="form-group form-float" hidden="true">
								<div class="form-line">
									<input type="text" id="answerBooklet" class="form-control">
									<label class="form-label">Answer Booklet Serial No.:</label>
								</div>
							</div>
						</p>
						<p>
							Semester: <span id="attendenceSemester"></span>
						</p>
						<p>
							AcademicYear: <span id="attendenceAcademicYear"></span>
						</p>
						<p>
							<div class="form-group form-float">
								<div class="form-line">
									<input type="text" id="otpCode" class="form-control">
									<label class="form-label">OTP Code</label>
								</div>
								<label id="otp-error"></label>
							</div>
						</p>
						<p>
							<button id="validateOTP" class="btn btn-primary waves-effect btn-block" role="button">Validate OTP</button>
						</p>
					</div>
				</div>
				
			</div>
			<div class="modal-footer">
				<button type="button" id="saveAttance" class="btn btn-link waves-effect">SAVE CHANGES</button>
				<button type="button" class="btn btn-link waves-effect" data-dismiss="modal">CLOSE</button>
			</div>
		</div>
	</div>
</div>

DEPTAT.UI/Views/Examination/AttendanceList.cshtml
@model IEnumerable<DEPTAT.Application.Responses.AttendanceResponse>

<div class="row clearfix">
    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
        <div class="card">
            <div class="header">
                <h2>
                    DETAILED ATTENDANCE LIST
                </h2>
                <ul class="header-dropdown m-r--5">
                    <li class="dropdown">
                        <a href="javascript:void(0);" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
                            <i class="material-icons">more_vert</i>
                        </a>
                        <ul class="dropdown-menu pull-right">
                            <li><a asp-controller="Examination" asp-action="Attendance">TAKE ATTENDANCE</a></li>
                        </ul>
                    </li>
                </ul>
            </div>
            <div class="body">
                @if (Model.Count() != 0)
                {
                    <div class="table-responsive">
                        <table class="table table-bordered table-striped table-hover dataTable js-exportable">
                            <thead>
                            <tr>
                                
                                    <th>Student Number</th>
                                    <th>Name</th>
                                    <th>Answer Book Serial No.</th>
                                    <th>Semester</th>
                                    <th>AcademicYear</th>
                                    <th>CourseCode</th>
                                    <th>OTP Code</th>
                                <th>Created By</th>
                            </tr>
                            </thead>
                            <tbody>
                                @if (Model.Any())
                                {
                                    @foreach (var data in Model)
                                    {
                                        <tr>
                                            <td>@data.StudentNumber</td>
                                            <td>@data.Student.FullName</td>
                                            <td>@data.AnswerBookSerialNumber</td>
                                            <td>@data.Semester</td>
                                            <td>@data.AcademicYear</td>
                                            <td>@data.CourseCode</td>
                                            <td>@data.OtpCode</td>
                                            <td>@data.CreatedBy</td>
                                            
                                        </tr>
                                    }

                                }
                                else
                                {
                                    <tr>
                                        <td colspan="3">Nothing found</td>

                                    </tr>
                                }
                            </tbody>
                        </table>
                    </div>
                }
                else
                {
                    <div class="alert bg-green alert-dismissible" role="alert">
                        <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                        Sorry no records found...
                    </div>
                }
            </div>

        </div>
    </div>
</div>
<!-- #END# Exportable Table -->

DEPTAT.UI/Views/Examination/ClockStudent.cshtml
@*@model IEnumerable<DEPTAT.Application.Responses.DebtorsResponse>*@
@{
	//var programmeList = ViewBag.ProgrammeList as List<ProgrammeResponse>;
	//var studentListList = ViewBag.StudentList as List<StudentResponse>;
}
<div class="container-fluid">

	<!-- Horizontal Layout -->
	<div class="row clearfix">
		<div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
			<div class="card">
				<div class="header">
					<h2>
						CLOCK ATTENDANCE
					</h2>
					<div align="center">
					</div>
					<ul class="header-dropdown m-r--5">
						@*<li class="dropdown">
						<a href="javascript:void(0);" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
						<i class="material-icons">more_vert</i>
						</a>
						<ul class="dropdown-menu pull-right">
						<li><a href="javascript:void(0);">Add Data</a></li>
						<li><a href="~/uploads/template/DebtTemplate.xlsx">Download Template</a></li>
						<li><a href="javascript:void(0);">Something else here</a></li>
						</ul>
						</li>*@
					</ul>
				</div>
				<div class="body">
					@*<form action="/target" class="dropzone" id="my-form"></form>*@
					<form class="form-horizontal" id="registerForm" method="GET">

						<div class="row clearfix">
							<div class="col-lg-2 col-md-2 col-sm-4 col-xs-4 form-control-label">
								<label for="file">Student Number:</label>
							</div>
							<div class="col-lg-4 col-md-5 col-sm-4 col-xs-4">
								<div class="form-group form-float">
									<div class="form-line">
										<input type="text" class="form-control" id="studentNumber" name="StudentNumber" required="" aria-required="true">
										<label class="form-label">Search Student</label>
									</div>
								</div>
							</div>
							<button type="button" id="searchStudent" class="btn btn-primary">Search</button>

							

						</div>
					</form>
				</div>
			</div>
		</div>
	</div>
	<!-- #END# Horizontal Layout -->
	<!-- Horizontal Layout -->
	<div class="row clearfix">
		<div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
			<div class="card">
				<div class="header">
					<h2>
						STUDENTS
					</h2>

				</div>
				<div class="body">
					<div class="row">
						<div style="display: flex;
						            align-items: center;
						            justify-content: center;
						            height: 100%;">
							<div class="col-sm-6 col-md-3">
								<div id="showData"></div>
							</div>
						</div>
						
					</div>
				</div>
			</div>
		</div>
	</div>
	<!-- #END# Horizontal Layout -->

</div>


<script type="text/ecmascript">
	$(document).ready(function() {
			
		function generateRandomOTP(length) {
			const charset = "0123456789";
			let OTP = "";
			for (let i = 0; i < length; i++) {
				const randomIndex = Math.floor(Math.random() * charset.length);
				OTP += charset[randomIndex];
			}
			return OTP;
		}

		
			$(document).on('click', '#otp', function () {
					$("#clockAttendance").show();
						$("#otp").hide();
				// Generate a random 6-digit OTP code
				const otpCode = generateRandomOTP(6);
				// Display the OTP code on the page
				$('#studentOTP').text(otpCode);

			});
		
		
		
		
		
		


		//Upate Year Group
	$('#searchStudent').click(function() {

		var studentNumber = $('#studentNumber').val();
		var baseurl = $('#base_url').text();
		var output =``;


		$.ajax({
			url: $('#base_url').text() + '/Examination/SearchStudent',
			contentType: "application/json",
			type: 'GET',

			//data: JSON.stringify(updateDebtor),
			data: {StudentNumber: studentNumber},
			success: function(response) {
				if (response.isSuccess) {
					if(response.result != null){
					output =`
						<div class="thumbnail">
									<img src="${baseurl}/uploads/${response.result.student.imageUrl}">
									<div class="caption">
										<h3>Student Number: <span id="studentNUmber">${response.result.studentNumber}</span></h3>
										<h3>OTP: <span id="studentOTP"></span></h3>
										<p>
											Don't forget the generated Code, It will be used for your attendance
										</p>
										<p>
											<button type="button" style="display: flex;
													  align-items: center;
													  justify-content: center;
													  height: 100%;"  id="otp" class="btn btn-primary btn-block waves-effect" role="button">Generate OTP</button>
										</p>
										<p>
											<button type="button" style="display: flex;
													  align-items: center;
													  justify-content: center;
													  height: 100%;" id="clockAttendance" class="btn btn-success btn-block waves-effect" role="button">Clock</button>
										</p>
									</div>
								</div>

					`;
					}else{
						output =`
					<div class="alert bg-green alert-dismissible" role="alert">
								<button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">×</span></button>
								Sorry no bill record found
							</div>
					`;

						}

				} else {
					output =`
					<div class="alert bg-green alert-dismissible" role="alert">
								<button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">×</span></button>
								Sorry no Student record found
							</div>
					`;
				}
					$('#showData').html(output);
						$("#clockAttendance").hide();
			}

		});
	});
	
})
</script>
<script>
	$(document).ready(function() {
		
		$(document).on('click',
			'#clockAttendance',
			function() {
				
				var otp = $("#studentOTP").text();
				var studentNumber = $("#studentNUmber").text();
			
				var data = {
					"OtpCode": otp,
					"StudentNumber": studentNumber
				}

				$.ajax({
					url: $('#base_url').text() + '/Examination/ClockAttendance',
					type: 'POST', // Explicitly set the HTTP method to POST
					contentType: 'application/json',
					data: JSON.stringify(data),
					//data: data,
					success: function(response) {
// Handle the response here
						if (response.isSuccess) {
							showNotificationSuccessMessage(response.message, "Success");
						} else {
							showNotificationErrorMessage("Failed", response.message, "error");
						}
						$("#otp").show();
						setTimeout(function() {
							window.location.reload();
						}, 5000);
					},
					error: function(xhr, status, error) {
// Handle any errors here
						showNotificationErrorMessage("Failed", error, "error");
					}
				});
			});
	})
</script>

DEPTAT.UI/Views/Examination/ViewOTP.cshtml
@model IEnumerable<DEPTAT.Application.Responses.OtpResponse>

<div class="row clearfix">
    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
        <div class="card">
            <div class="header">
                <h2>
                    DETAILED PROGRAMME VIEW
                </h2>
                @*<ul class="header-dropdown m-r--5">
                    <li class="dropdown">
                        <a href="javascript:void(0);" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
                            <i class="material-icons">more_vert</i>
                        </a>
                        <ul class="dropdown-menu pull-right">
                            <li><a asp-controller="Programme" asp-action="Index">Add Programme</a></li>
                        </ul>
                    </li>
                </ul>*@
            </div>
            <div class="body">
                @if (Model.Count() != 0)
                {
                    <div class="table-responsive">
                        <table class="table table-bordered table-striped table-hover dataTable js-exportable">
                            <thead>
                                <tr>
                                    <th>Image</th>
                                    <th>Student Number</th>
                                    <th>Name</th>
                                    <th>OTP</th>
                                    <th>Year</th>
                                </tr>
                            </thead>
                            <tbody>
                                @if (Model.Any())
                                {
                                    @foreach (var data in Model)
                                    {
                                        <tr>
                                            <td><img src="~/uploads/@data.Student.ImageUrl" style="width: 10%; height: 10%" /></td>
                                            <td>@data.StudentNumber</td>

                                            <td>@data.Student.FullName</td>
                                            <td>@data.OtpCode</td>
                                            <td>@data.CurrentYear</td>

                                        </tr>
                                    }

                                }
                                else
                                {
                                    <tr>
                                        <td colspan="3">Nothing found</td>

                                    </tr>
                                }
                            </tbody>
                        </table>
                    </div>
                }
                else
                {
                    <div class="alert bg-green alert-dismissible" role="alert">
                        <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                        Sorry no records found...
                    </div>
                }
            </div>
        </div>
    </div>
</div>
<!-- #END# Exportable Table -->